name: 'Code Analysis'

on:
  push:
    branches:
      - chore/support-github-actions
  pull_request:
    branches:
      - main

jobs:
  unit-testing:
    name: "Code Analysis"
    runs-on: ubuntu-20.04
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Codacy Analyze Tool
        run: |
         curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | \
         tar xvz && cd codacy-analysis-cli-* && sudo make install \
         && cd .. && rm -rf master.* codacy-analysis-cli-*

      - name: Run aligncheck
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
         codacy-analysis-cli analyze --provider gh \
         --username leroy-merlin-br \
         --project logstash_exporter \
         --tool aligncheck \
         --allow-network \
         --upload \
         --verbose
